
        DROP TABLE IF EXISTS CA;


        
        DROP TABLE IF EXISTS DE;


        
        DROP TABLE IF EXISTS FR;


        
        DROP TABLE IF EXISTS GB;


        
        DROP TABLE IF EXISTS INN;


        
        DROP TABLE IF EXISTS JP;


        
        DROP TABLE IF EXISTS KR;


        
        DROP TABLE IF EXISTS MX;


        
        DROP TABLE IF EXISTS RU;


        
        DROP TABLE IF EXISTS US;


        