

\COPY CAvideos (video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description) FROM '/home/sheyla/Documentos/Semestre2/Ines/archive1/CAvideos1.csv' WITH (FORMAT csv, DELIMITER ',', NULL '', HEADER TRUE);



\COPY DEvideos (video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description) FROM '/home/sheyla/Documentos/Semestre2/Ines/archive1/DEvideos1.csv' WITH (FORMAT csv, DELIMITER ',', NULL '', HEADER TRUE);



\COPY FRvideos (video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description) FROM '/home/sheyla/Documentos/Semestre2/Ines/archive1/FRvideos1.csv' WITH (FORMAT csv, DELIMITER ',', NULL '', HEADER TRUE);



\COPY GBvideos (video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description) FROM '/home/sheyla/Documentos/Semestre2/Ines/archive1/GBvideos1.csv' WITH (FORMAT csv, DELIMITER ',', NULL '', HEADER TRUE);



\COPY INvideos (video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description) FROM '/home/sheyla/Documentos/Semestre2/Ines/archive1/INvideos1.csv' WITH (FORMAT csv, DELIMITER ',', NULL '', HEADER TRUE);



\COPY JPvideos (video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description) FROM '/home/sheyla/Documentos/Semestre2/Ines/archive1/JPvideos1.csv' WITH (FORMAT csv, DELIMITER ',', NULL '', HEADER TRUE);



\COPY KRvideos (video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description) FROM '/home/sheyla/Documentos/Semestre2/Ines/archive1/KRvideos1.csv' WITH (FORMAT csv, DELIMITER ',', NULL '', HEADER TRUE);



\COPY MXvideos (video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description) FROM '/home/sheyla/Documentos/Semestre2/Ines/archive1/MXvideos1.csv' WITH (FORMAT csv, DELIMITER ',', NULL '', HEADER TRUE);



\COPY RUvideos (video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description) FROM '/home/sheyla/Documentos/Semestre2/Ines/archive1/RUvideos1.csv' WITH (FORMAT csv, DELIMITER ',', NULL '', HEADER TRUE);



\COPY USvideos (video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description) FROM '/home/sheyla/Documentos/Semestre2/Ines/archive1/USvideos1.csv' WITH (FORMAT csv, DELIMITER ',', NULL '', HEADER TRUE);

