

        \COPY CA_category (id,category) FROM '/home/sheyla/Documentos/Semestre2/Ines/archive1/CA_category_id.csv' WITH (FORMAT csv, DELIMITER ',', NULL '', HEADER TRUE);
   
        

        \COPY DE_category (id,category) FROM '/home/sheyla/Documentos/Semestre2/Ines/archive1/DE_category_id.csv' WITH (FORMAT csv, DELIMITER ',', NULL '', HEADER TRUE);
   
        

        \COPY FR_category (id,category) FROM '/home/sheyla/Documentos/Semestre2/Ines/archive1/FR_category_id.csv' WITH (FORMAT csv, DELIMITER ',', NULL '', HEADER TRUE);
   
        

        \COPY GB_category (id,category) FROM '/home/sheyla/Documentos/Semestre2/Ines/archive1/GB_category_id.csv' WITH (FORMAT csv, DELIMITER ',', NULL '', HEADER TRUE);
   
        

        \COPY IN_category (id,category) FROM '/home/sheyla/Documentos/Semestre2/Ines/archive1/IN_category_id.csv' WITH (FORMAT csv, DELIMITER ',', NULL '', HEADER TRUE);
   
        

        \COPY JP_category (id,category) FROM '/home/sheyla/Documentos/Semestre2/Ines/archive1/JP_category_id.csv' WITH (FORMAT csv, DELIMITER ',', NULL '', HEADER TRUE);
   
        

        \COPY KR_category (id,category) FROM '/home/sheyla/Documentos/Semestre2/Ines/archive1/KR_category_id.csv' WITH (FORMAT csv, DELIMITER ',', NULL '', HEADER TRUE);
   
        

        \COPY MX_category (id,category) FROM '/home/sheyla/Documentos/Semestre2/Ines/archive1/MX_category_id.csv' WITH (FORMAT csv, DELIMITER ',', NULL '', HEADER TRUE);
   
        

        \COPY RU_category (id,category) FROM '/home/sheyla/Documentos/Semestre2/Ines/archive1/RU_category_id.csv' WITH (FORMAT csv, DELIMITER ',', NULL '', HEADER TRUE);
   
        

        \COPY US_category (id,category) FROM '/home/sheyla/Documentos/Semestre2/Ines/archive1/US_category_id.csv' WITH (FORMAT csv, DELIMITER ',', NULL '', HEADER TRUE);
   
        