
        DROP TABLE IF EXISTS CAvideos;

        
        CREATE TABLE CAvideos
        (
            video_id                CHAR(20),
            trending_date           DATE,
            title                   CHAR(500),    
            channel_title           CHAR(200),
            category_id             INTEGER,
            publish_time            TIMESTAMP,
            tags                    CHAR(1500),   
            views                   INTEGER,
            likes                   INTEGER,
            dislikes                INTEGER,
            comment_count           INTEGER,
            thumbnail_link          CHAR(100),
            comments_disabled       BOOLEAN,
            ratings_disabled        BOOLEAN,
            video_error_or_removed  BOOLEAN,
            description             CHAR(12000)

        );
        



        
        DROP TABLE IF EXISTS DEvideos;

        
        CREATE TABLE DEvideos
        (
            video_id                CHAR(20),
            trending_date           DATE,
            title                   CHAR(500),    
            channel_title           CHAR(200),
            category_id             INTEGER,
            publish_time            TIMESTAMP,
            tags                    CHAR(1500),   
            views                   INTEGER,
            likes                   INTEGER,
            dislikes                INTEGER,
            comment_count           INTEGER,
            thumbnail_link          CHAR(100),
            comments_disabled       BOOLEAN,
            ratings_disabled        BOOLEAN,
            video_error_or_removed  BOOLEAN,
            description             CHAR(12000)

        );
        



        
        DROP TABLE IF EXISTS FRvideos;

        
        CREATE TABLE FRvideos
        (
            video_id                CHAR(20),
            trending_date           DATE,
            title                   CHAR(500),    
            channel_title           CHAR(200),
            category_id             INTEGER,
            publish_time            TIMESTAMP,
            tags                    CHAR(1500),   
            views                   INTEGER,
            likes                   INTEGER,
            dislikes                INTEGER,
            comment_count           INTEGER,
            thumbnail_link          CHAR(100),
            comments_disabled       BOOLEAN,
            ratings_disabled        BOOLEAN,
            video_error_or_removed  BOOLEAN,
            description             CHAR(12000)

        );
        



        
        DROP TABLE IF EXISTS GBvideos;

        
        CREATE TABLE GBvideos
        (
            video_id                CHAR(20),
            trending_date           DATE,
            title                   CHAR(500),    
            channel_title           CHAR(200),
            category_id             INTEGER,
            publish_time            TIMESTAMP,
            tags                    CHAR(1500),   
            views                   INTEGER,
            likes                   INTEGER,
            dislikes                INTEGER,
            comment_count           INTEGER,
            thumbnail_link          CHAR(100),
            comments_disabled       BOOLEAN,
            ratings_disabled        BOOLEAN,
            video_error_or_removed  BOOLEAN,
            description             CHAR(12000)

        );
        



        
        DROP TABLE IF EXISTS INvideos;

        
        CREATE TABLE INvideos
        (
            video_id                CHAR(20),
            trending_date           DATE,
            title                   CHAR(500),    
            channel_title           CHAR(200),
            category_id             INTEGER,
            publish_time            TIMESTAMP,
            tags                    CHAR(1500),   
            views                   INTEGER,
            likes                   INTEGER,
            dislikes                INTEGER,
            comment_count           INTEGER,
            thumbnail_link          CHAR(100),
            comments_disabled       BOOLEAN,
            ratings_disabled        BOOLEAN,
            video_error_or_removed  BOOLEAN,
            description             CHAR(12000)

        );
        



        
        DROP TABLE IF EXISTS JPvideos;

        
        CREATE TABLE JPvideos
        (
            video_id                CHAR(20),
            trending_date           DATE,
            title                   CHAR(500),    
            channel_title           CHAR(200),
            category_id             INTEGER,
            publish_time            TIMESTAMP,
            tags                    CHAR(1500),   
            views                   INTEGER,
            likes                   INTEGER,
            dislikes                INTEGER,
            comment_count           INTEGER,
            thumbnail_link          CHAR(100),
            comments_disabled       BOOLEAN,
            ratings_disabled        BOOLEAN,
            video_error_or_removed  BOOLEAN,
            description             CHAR(12000)

        );
        



        
        DROP TABLE IF EXISTS KRvideos;

        
        CREATE TABLE KRvideos
        (
            video_id                CHAR(20),
            trending_date           DATE,
            title                   CHAR(500),    
            channel_title           CHAR(200),
            category_id             INTEGER,
            publish_time            TIMESTAMP,
            tags                    CHAR(1500),   
            views                   INTEGER,
            likes                   INTEGER,
            dislikes                INTEGER,
            comment_count           INTEGER,
            thumbnail_link          CHAR(100),
            comments_disabled       BOOLEAN,
            ratings_disabled        BOOLEAN,
            video_error_or_removed  BOOLEAN,
            description             CHAR(12000)

        );
        



        
        DROP TABLE IF EXISTS MXvideos;

        
        CREATE TABLE MXvideos
        (
            video_id                CHAR(20),
            trending_date           DATE,
            title                   CHAR(500),    
            channel_title           CHAR(200),
            category_id             INTEGER,
            publish_time            TIMESTAMP,
            tags                    CHAR(1500),   
            views                   INTEGER,
            likes                   INTEGER,
            dislikes                INTEGER,
            comment_count           INTEGER,
            thumbnail_link          CHAR(100),
            comments_disabled       BOOLEAN,
            ratings_disabled        BOOLEAN,
            video_error_or_removed  BOOLEAN,
            description             CHAR(12000)

        );
        



        
        DROP TABLE IF EXISTS RUvideos;

        
        CREATE TABLE RUvideos
        (
            video_id                CHAR(20),
            trending_date           DATE,
            title                   CHAR(500),    
            channel_title           CHAR(200),
            category_id             INTEGER,
            publish_time            TIMESTAMP,
            tags                    CHAR(1500),   
            views                   INTEGER,
            likes                   INTEGER,
            dislikes                INTEGER,
            comment_count           INTEGER,
            thumbnail_link          CHAR(100),
            comments_disabled       BOOLEAN,
            ratings_disabled        BOOLEAN,
            video_error_or_removed  BOOLEAN,
            description             CHAR(12000)

        );
        



        
        DROP TABLE IF EXISTS USvideos;

        
        CREATE TABLE USvideos
        (
            video_id                CHAR(20),
            trending_date           DATE,
            title                   CHAR(500),    
            channel_title           CHAR(200),
            category_id             INTEGER,
            publish_time            TIMESTAMP,
            tags                    CHAR(1500),   
            views                   INTEGER,
            likes                   INTEGER,
            dislikes                INTEGER,
            comment_count           INTEGER,
            thumbnail_link          CHAR(100),
            comments_disabled       BOOLEAN,
            ratings_disabled        BOOLEAN,
            video_error_or_removed  BOOLEAN,
            description             CHAR(12000)

        );
        



        