
        DROP TABLE IF EXISTS CA_category;        
        CREATE TABLE CA_category(
            id INTEGER,
            category CHAR(50));
    
        
        DROP TABLE IF EXISTS DE_category;        
        CREATE TABLE DE_category(
            id INTEGER,
            category CHAR(50));
    
        
        DROP TABLE IF EXISTS FR_category;        
        CREATE TABLE FR_category(
            id INTEGER,
            category CHAR(50));
    
        
        DROP TABLE IF EXISTS GB_category;        
        CREATE TABLE GB_category(
            id INTEGER,
            category CHAR(50));
    
        
        DROP TABLE IF EXISTS IN_category;        
        CREATE TABLE IN_category(
            id INTEGER,
            category CHAR(50));
    
        
        DROP TABLE IF EXISTS JP_category;        
        CREATE TABLE JP_category(
            id INTEGER,
            category CHAR(50));
    
        
        DROP TABLE IF EXISTS KR_category;        
        CREATE TABLE KR_category(
            id INTEGER,
            category CHAR(50));
    
        
        DROP TABLE IF EXISTS MX_category;        
        CREATE TABLE MX_category(
            id INTEGER,
            category CHAR(50));
    
        
        DROP TABLE IF EXISTS RU_category;        
        CREATE TABLE RU_category(
            id INTEGER,
            category CHAR(50));
    
        
        DROP TABLE IF EXISTS US_category;        
        CREATE TABLE US_category(
            id INTEGER,
            category CHAR(50));
    
        