
        DROP TABLE IF EXISTS CA_datos;

        
        CREATE TABLE CA_datos
        (
            video_id                CHAR(20),
            trending_date           DATE,
            title                   CHAR(500),    
            channel_title           CHAR(200),
            publish_time            TIMESTAMP,
            tags                    CHAR(1500),   
            views                   INTEGER,
            likes                   INTEGER,
            dislikes                INTEGER,
            comment_count           INTEGER,
            thumbnail_link          CHAR(100),
            comments_disabled       BOOLEAN,
            ratings_disabled        BOOLEAN,
            video_error_or_removed  BOOLEAN,
            description             CHAR(12000),
            category                CHAR(50)

        );
        



        
        DROP TABLE IF EXISTS DE_datos;

        
        CREATE TABLE DE_datos
        (
            video_id                CHAR(20),
            trending_date           DATE,
            title                   CHAR(500),    
            channel_title           CHAR(200),
            publish_time            TIMESTAMP,
            tags                    CHAR(1500),   
            views                   INTEGER,
            likes                   INTEGER,
            dislikes                INTEGER,
            comment_count           INTEGER,
            thumbnail_link          CHAR(100),
            comments_disabled       BOOLEAN,
            ratings_disabled        BOOLEAN,
            video_error_or_removed  BOOLEAN,
            description             CHAR(12000),
            category                CHAR(50)

        );
        



        
        DROP TABLE IF EXISTS FR_datos;

        
        CREATE TABLE FR_datos
        (
            video_id                CHAR(20),
            trending_date           DATE,
            title                   CHAR(500),    
            channel_title           CHAR(200),
            publish_time            TIMESTAMP,
            tags                    CHAR(1500),   
            views                   INTEGER,
            likes                   INTEGER,
            dislikes                INTEGER,
            comment_count           INTEGER,
            thumbnail_link          CHAR(100),
            comments_disabled       BOOLEAN,
            ratings_disabled        BOOLEAN,
            video_error_or_removed  BOOLEAN,
            description             CHAR(12000),
            category                CHAR(50)

        );
        



        
        DROP TABLE IF EXISTS GB_datos;

        
        CREATE TABLE GB_datos
        (
            video_id                CHAR(20),
            trending_date           DATE,
            title                   CHAR(500),    
            channel_title           CHAR(200),
            publish_time            TIMESTAMP,
            tags                    CHAR(1500),   
            views                   INTEGER,
            likes                   INTEGER,
            dislikes                INTEGER,
            comment_count           INTEGER,
            thumbnail_link          CHAR(100),
            comments_disabled       BOOLEAN,
            ratings_disabled        BOOLEAN,
            video_error_or_removed  BOOLEAN,
            description             CHAR(12000),
            category                CHAR(50)

        );
        



        
        DROP TABLE IF EXISTS IN_datos;

        
        CREATE TABLE IN_datos
        (
            video_id                CHAR(20),
            trending_date           DATE,
            title                   CHAR(500),    
            channel_title           CHAR(200),
            publish_time            TIMESTAMP,
            tags                    CHAR(1500),   
            views                   INTEGER,
            likes                   INTEGER,
            dislikes                INTEGER,
            comment_count           INTEGER,
            thumbnail_link          CHAR(100),
            comments_disabled       BOOLEAN,
            ratings_disabled        BOOLEAN,
            video_error_or_removed  BOOLEAN,
            description             CHAR(12000),
            category                CHAR(50)

        );
        



        
        DROP TABLE IF EXISTS JP_datos;

        
        CREATE TABLE JP_datos
        (
            video_id                CHAR(20),
            trending_date           DATE,
            title                   CHAR(500),    
            channel_title           CHAR(200),
            publish_time            TIMESTAMP,
            tags                    CHAR(1500),   
            views                   INTEGER,
            likes                   INTEGER,
            dislikes                INTEGER,
            comment_count           INTEGER,
            thumbnail_link          CHAR(100),
            comments_disabled       BOOLEAN,
            ratings_disabled        BOOLEAN,
            video_error_or_removed  BOOLEAN,
            description             CHAR(12000),
            category                CHAR(50)

        );
        



        
        DROP TABLE IF EXISTS KR_datos;

        
        CREATE TABLE KR_datos
        (
            video_id                CHAR(20),
            trending_date           DATE,
            title                   CHAR(500),    
            channel_title           CHAR(200),
            publish_time            TIMESTAMP,
            tags                    CHAR(1500),   
            views                   INTEGER,
            likes                   INTEGER,
            dislikes                INTEGER,
            comment_count           INTEGER,
            thumbnail_link          CHAR(100),
            comments_disabled       BOOLEAN,
            ratings_disabled        BOOLEAN,
            video_error_or_removed  BOOLEAN,
            description             CHAR(12000),
            category                CHAR(50)

        );
        



        
        DROP TABLE IF EXISTS MX_datos;

        
        CREATE TABLE MX_datos
        (
            video_id                CHAR(20),
            trending_date           DATE,
            title                   CHAR(500),    
            channel_title           CHAR(200),
            publish_time            TIMESTAMP,
            tags                    CHAR(1500),   
            views                   INTEGER,
            likes                   INTEGER,
            dislikes                INTEGER,
            comment_count           INTEGER,
            thumbnail_link          CHAR(100),
            comments_disabled       BOOLEAN,
            ratings_disabled        BOOLEAN,
            video_error_or_removed  BOOLEAN,
            description             CHAR(12000),
            category                CHAR(50)

        );
        



        
        DROP TABLE IF EXISTS RU_datos;

        
        CREATE TABLE RU_datos
        (
            video_id                CHAR(20),
            trending_date           DATE,
            title                   CHAR(500),    
            channel_title           CHAR(200),
            publish_time            TIMESTAMP,
            tags                    CHAR(1500),   
            views                   INTEGER,
            likes                   INTEGER,
            dislikes                INTEGER,
            comment_count           INTEGER,
            thumbnail_link          CHAR(100),
            comments_disabled       BOOLEAN,
            ratings_disabled        BOOLEAN,
            video_error_or_removed  BOOLEAN,
            description             CHAR(12000),
            category                CHAR(50)

        );
        



        
        DROP TABLE IF EXISTS US_datos;

        
        CREATE TABLE US_datos
        (
            video_id                CHAR(20),
            trending_date           DATE,
            title                   CHAR(500),    
            channel_title           CHAR(200),
            publish_time            TIMESTAMP,
            tags                    CHAR(1500),   
            views                   INTEGER,
            likes                   INTEGER,
            dislikes                INTEGER,
            comment_count           INTEGER,
            thumbnail_link          CHAR(100),
            comments_disabled       BOOLEAN,
            ratings_disabled        BOOLEAN,
            video_error_or_removed  BOOLEAN,
            description             CHAR(12000),
            category                CHAR(50)

        );
        



        